# Generated by Django 4.0.4 on 2022-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgt_app', '0002_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAddRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_number', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fees',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='ShoppingTemp',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
    ]
