# Generated by Django 4.0.4 on 2022-11-16 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgt_app', '0003_transportaddroute_remove_fees_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Warden')], default=1, max_length=10),
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('profile_pic', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_mgt_app.hostel')),
            ],
        ),
    ]
